---
- name: Установка мониторинга
  hosts: all
  serial: 1
  become: yes
  vars:
      node_exporter_version: "1.8.2"
      node_exporter_port: 9229
  tasks:
      - name: Создать пользователя node_exporter
        user:
            name: node_exporter
            system: yes
            shell: /sbin/nologin
            home: /var/lib/node_exporter

      - name: Скачать Node Exporter
        get_url:
            url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
            dest: /tmp/node_exporter.tar.gz
            mode: "0644"

      - name: Распаковать Node Exporter
        unarchive:
            src: /tmp/node_exporter.tar.gz
            dest: /tmp/
            remote_src: yes
            creates: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64

      - name: Переместить Node Exporter в /usr/local/bin
        copy:
            src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
            dest: /usr/local/bin/node_exporter
            mode: "0755"
            remote_src: yes

      - name: Создать systemd сервис для Node Exporter
        copy:
            dest: /etc/systemd/system/node_exporter.service
            content: |
                [Unit]
                Description=Node Exporter
                After=network.target

                [Service]
                User=node_exporter
                Group=node_exporter
                Type=simple
                ExecStart=/usr/local/bin/node_exporter --web.listen-address=:{{ node_exporter_port }}

                [Install]
                WantedBy=multi-user.target
            mode: "0644"

      - name: Включить и запустить Node Exporter
        systemd:
            name: node_exporter
            state: started
            enabled: yes
            daemon_reload: yes

      - name: Очистить временные файлы
        file:
            path: /tmp/node_exporter.tar.gz
            state: absent
        ignore_errors: yes
