---
- name: 🧹 Удалить A-записи неактивных нод из Porkbun
  hosts: localhost
  gather_facts: no

  vars:
    domains_to_process: "{{ target_domains }}"  # Домены 2-го уровня (apex)

  tasks:

    # --- ШАГ 1: Получить список нод из Remnawave ---
    - name: 🌐 Получить все ноды из Remnawave
      uri:
        url: "https://{{ remnawave_domain }}/api/nodes"
        method: GET
        headers:
          Authorization: "Bearer {{ remnawave_token }}"
        return_content: yes
        timeout: 30
      register: remnawave_response
      until: remnawave_response.status == 200
      retries: 3
      delay: 5

    - name: ❌ Проверить ошибку Remnawave API
      fail:
        msg: "Remnawave API вернул ошибку: {{ remnawave_response.json.message | default('Unknown error') }}"
      when: remnawave_response.json is defined and remnawave_response.json.errorCode is defined

    - name: 🧩 Извлечь активные и неактивные ноды
      set_fact:
        active_nodes: >-
          {{
            remnawave_response.json.response
            | selectattr('isNodeOnline', 'equalto', true)
            | list
          }}
        inactive_nodes: >-
          {{
            remnawave_response.json.response
            | selectattr('isNodeOnline', 'equalto', false)
            | list
          }}

    - name: 📄 Вывести список активных и неактивных нод
      debug:
        msg: |-
          АКТИВНЫЕ НОДЫ ({{ active_nodes | length }} шт.):
          {% for node in active_nodes %}
          {{ "%2d" % loop.index }}) {{ node.name }} → {{ node.address }}
          {% endfor %}
          ---
          НЕАКТИВНЫЕ НОДЫ ({{ inactive_nodes | length }} шт.):
          {% for node in inactive_nodes %}
          {{ "%2d" % loop.index }}) {{ node.name }} → {{ node.address }}
          {% endfor %}

    - name: 🟡 Нет неактивных нод — пропускаем удаление
      debug:
        msg: "Нет неактивных нод в Remnawave. Удаление DNS не требуется."
      when: inactive_nodes | length == 0

    # --- ШАГ 2: Получить все DNS-записи для каждого домена ---
    - name: 🔍 Получить все DNS-записи для домена
      uri:
        url: "https://api.porkbun.com/api/json/v3/dns/retrieve/{{ item }}"
        method: POST
        body:
          apikey: "{{ porkbun_api_key }}"
          secretapikey: "{{ porkbun_secret_api_key }}"
        body_format: json
        return_content: yes
      register: dns_retrieve_results
      ignore_errors: yes
      loop: "{{ domains_to_process }}"
      loop_control:
        label: "{{ item }}"

    # --- ШАГ 3: Проверить ошибки Porkbun API ---
    - name: ❌ Проверить ошибки Porkbun API
      fail:
        msg: "Porkbun API error for {{ item }}: {{ result.json.message | default('Unknown') }}"
      when: result.json is defined and result.json.status != "SUCCESS"
      loop: "{{ domains_to_process }}"
      loop_control:
        label: "{{ item }}"
      vars:
        result: "{{ dns_retrieve_results.results | selectattr('item', 'equalto', item) | first }}"

    # --- ШАГ 4: Собрать текущие A-записи ---
    - name: 🧩 Построить existing_ips_map (A-записи apex-доменов)
      set_fact:
        existing_ips_map: >-
          {%
            set result = existing_ips_map | default({})
          %}
          {%
            for domain in domains_to_process
          %}
            {%
              set records = (
                (dns_retrieve_results.results | selectattr('item', 'equalto', domain) | first).json.records | default([])
              )
              | selectattr('type', 'equalto', 'A')
              | selectattr('name', 'equalto', domain)
              | map(attribute='content')
              | map('trim')
              | list
            %}
            {%
              set _ = result.update({domain: records})
            %}
          {%
            endfor
          %}
          {{ result }}
      when: dns_retrieve_results is defined

    - name: 🐞 DEBUG — existing_ips_map
      debug:
        var: existing_ips_map

    # --- ШАГ 5: Определить IP неактивных нод, которые нужно удалить ---
    - name: 🧩 Построить inactive_ips_map
      set_fact:
        inactive_ips_map: >-
          {{
            inactive_ips_map | default({}) | combine({
              domain: (
                existing_ips_map[domain] | default([]) | map('trim') | list
                | intersect(inactive_nodes | map(attribute='address') | map('trim') | list)
              )
            })
          }}
      loop: "{{ domains_to_process }}"
      loop_control:
        loop_var: domain
        label: "{{ domain }}"

    - name: 🐞 DEBUG — inactive_ips_map (IP для удаления)
      debug:
        var: inactive_ips_map

    # --- ШАГ 6: Удалить A-записи для неактивных IP ---
    - name: 🗑️ Удалить A-записи неактивных нод
      vars:
        domain: "{{ item }}"
        records: "{{ (dns_retrieve_results.results | selectattr('item', 'equalto', domain) | first).json.records | default([]) }}"
      loop: "{{ domains_to_process }}"
      loop_control:
        label: "{{ item }}"
      when: inactive_ips_map[domain] | length > 0
      block:

        - name: 🧩 Найти записи для удаления
          set_fact:
            records_to_delete: >-
              {{
                records
                | selectattr('type', 'equalto', 'A')
                | selectattr('name', 'equalto', domain)
                | selectattr('content', 'in', inactive_ips_map[domain])
                | list
              }}

        - name: 🗑️ Удалить A-записи через API
          uri:
            url: "https://api.porkbun.com/api/json/v3/dns/delete/{{ domain }}/{{ record.id }}"
            method: POST
            body:
              apikey: "{{ porkbun_api_key }}"
              secretapikey: "{{ porkbun_secret_api_key }}"
            body_format: json
            status_code: 200
          loop: "{{ records_to_delete }}"
          loop_control:
            loop_var: record
            label: "{{ domain }} → {{ record.content }}"
          register: delete_results
          ignore_errors: yes

        - name: ✅ Отчёт об удалении
          debug:
            msg: |-
              ✅ Удалено записей в {{ domain }}: {{ delete_results.results | length }}
              {% for rec in delete_results.results %}
              - {{ domain }} → {{ rec.item.content }}
              {% endfor %}

    # --- ШАГ 7: Если удалять нечего ---
    - name: ℹ️ Нет записей для удаления
      debug:
        msg: "Все DNS A-записи соответствуют активным нодам — удалять нечего."
      when: inactive_ips_map | dict2items | map(attribute='value') | map('length') | sum == 0

    # --- ФИНАЛ: Итоговая сводка ---
    - name: 📊 Итоговая сводка
      debug:
        msg: |-
          Удаление завершено.

          Активных нод: {{ active_nodes | length }}
          Неактивных нод: {{ inactive_nodes | length }}
          Обработано доменов: {{ domains_to_process | length }}
