---
- name: 🧹 Удалить A-записи неактивных нод из Porkbun
  hosts: localhost
  gather_facts: no

  vars:
    domains_to_process: "{{ target_domains }}"  # Список доменов 2-го уровня
    remnawave_api_url: "https://{{ remnawave_domain }}/api/nodes"

  tasks:

    # --- ШАГ 1: Получаем список нод из Remnawave ---
    - name: 🌐 Получить список нод из Remnawave
      uri:
        url: "{{ remnawave_api_url }}"
        method: GET
        headers:
          Authorization: "Bearer {{ remnawave_token }}"
        return_content: yes
        timeout: 30
      register: remnawave_response
      until: remnawave_response.status == 200
      retries: 3
      delay: 5

    - name: ❌ Проверить ошибку Remnawave API
      fail:
        msg: "Remnawave API error: {{ remnawave_response.json.message | default('Unknown error') }}"
      when: remnawave_response.json.errorCode is defined

    - name: 🧩 Выделить активные и все IP
      set_fact:
        active_ips: >-
          {{
            remnawave_response.json.response
            | selectattr('isNodeOnline', 'equalto', true)
            | map(attribute='address')
            | map('trim')
            | list
            | unique
          }}
        all_ips: >-
          {{
            remnawave_response.json.response
            | map(attribute='address')
            | map('trim')
            | list
            | unique
          }}

    - name: 📊 Вывести активные IP
      debug:
        msg: |-
          Активные IP: {{ active_ips }}

    # --- ШАГ 2: Получить все DNS-записи ---
    - name: 🔍 Получить DNS-записи для каждого домена
      uri:
        url: "https://api.porkbun.com/api/json/v3/dns/retrieve/{{ item }}"
        method: POST
        body:
          apikey: "{{ porkbun_api_key }}"
          secretapikey: "{{ porkbun_secret_api_key }}"
        body_format: json
        return_content: yes
      register: dns_results
      loop: "{{ domains_to_process }}"
      loop_control:
        label: "{{ item }}"

    - name: 🧩 Собрать все A-записи по доменам
      set_fact:
        dns_a_map: >-
          {{
            dns_a_map | default({}) | combine({
              item: (
                (
                  (dns_results.results | selectattr('item', 'equalto', item) | first).json.records
                  | selectattr('type', 'equalto', 'A')
                  | selectattr('name', 'equalto', item)
                  | list
                )
              )
            })
          }}
      loop: "{{ domains_to_process }}"
      loop_control:
        label: "{{ item }}"

    - name: 🐞 DEBUG — dns_a_map (все A-записи)
      debug:
        var: dns_a_map

    # --- ШАГ 3: Определить неактивные IP (есть в DNS, но нет в Remnawave) ---
    - name: 🧩 Найти неактивные IP по доменам
      set_fact:
        inactive_ips_map: >-
          {{
            inactive_ips_map | default({}) | combine({
              domain: (
                (dns_a_map[domain] | map(attribute='content') | map('trim') | list)
                | difference(active_ips)
              )
            })
          }}
      loop: "{{ domains_to_process }}"
      loop_control:
        loop_var: domain
        label: "{{ domain }}"

    - name: 📋 Показать список неактивных IP
      debug:
        msg: |-
          Домен: {{ domain }}
          Неактивные IP для удаления: {{ inactive_ips_map[domain] }}
      loop: "{{ domains_to_process }}"
      loop_control:
        label: "{{ domain }}"

    # --- ШАГ 4: Удалить неактивные IP ---
    - name: 🗑️ Удалить A-записи с неактивными IP
      uri:
        url: "https://api.porkbun.com/api/json/v3/dns/delete/{{ domain }}/{{ record.id }}"
        method: POST
        body:
          apikey: "{{ porkbun_api_key }}"
          secretapikey: "{{ porkbun_secret_api_key }}"
        body_format: json
        status_code: 200
      loop: "{{ dns_a_map[domain] | selectattr('content', 'in', inactive_ips_map[domain]) | list }}"
      loop_control:
        loop_var: record
        label: "{{ domain }} → {{ record.content }}"
      vars:
        domain: "{{ item }}"
      with_items: "{{ domains_to_process }}"
      register: delete_results
      when: inactive_ips_map[domain] | length > 0

    # --- ШАГ 5: Итоговый отчёт ---
    - name: ✅ Отчёт об удалении
      debug:
        msg: |-
          Удаление завершено.
          {% for res in delete_results.results | default([]) %}
          - {{ res.item.0 if res.item is defined else '???' }} → {{ res.invocation.module_args.url | regex_replace('.*/dns/delete/', '') }}
          {% endfor %}
      when: delete_results is defined

    - name: ℹ️ Нет записей для удаления
      debug:
        msg: "Все DNS A-записи соответствуют активным нодам — удалять нечего."
      when: delete_results is not defined
