- name: Set Zabbix repo URL based on OS
  set_fact:
    zabbix_repo_url: >-
      {% if ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] | lower == 'ubuntu' %}
        https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu22.04_all.deb
      {% elif ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] | lower == 'debian' %}
        https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.0+debian12_all.deb
      {% else %}
        ""
      {% endif %}

- name: Fail if OS is not supported
  fail:
    msg: "This playbook supports only Debian and Ubuntu!"
  when: zabbix_repo_url == ""

- name: Show which OS and repo URL will be used
  debug:
    msg: "Detected OS: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} → Repo: {{ zabbix_repo_url }}"

- name: Download Zabbix repository package
  get_url:
    url: "{{ zabbix_repo_url }}"
    dest: /tmp/zabbix-release.deb
    mode: '0644'
  when: zabbix_repo_url != ""

- name: Install Zabbix repository
  apt:
    deb: /tmp/zabbix-release.deb
    state: present
  when: zabbix_repo_url != ""

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Zabbix Agent 2
  apt:
    name: zabbix-agent2
    state: present

- name: Install Zabbix Agent 2 plugins
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ zabbix_agent_plugins }}"

- name: Configure Zabbix Agent 2
  template:
    src: playbooks/templates/zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: '0644'
  register: config_changed

- name: Restart Zabbix Agent 2 if config changed
  systemd:
    name: zabbix-agent2
    state: restarted
  when: config_changed.changed

- name: Check if Docker is installed
  command: which docker
  register: docker_check
  ignore_errors: yes

- name: Set docker_installed fact
  set_fact:
    docker_installed: "{{ docker_check.rc == 0 }}"

- name: Add zabbix user to docker group
  user:
    name: zabbix
    groups: docker
    append: yes
  when: docker_installed

- name: Enable and start Zabbix Agent 2
  systemd:
    name: zabbix-agent2
    enabled: yes
    state: started

- name: Register host in Zabbix Server via API
  delegate_to: localhost
  run_once: true
  block:
    - name: Set Zabbix auth token
      set_fact:
        zabbix_auth_token: "{{ zabbix_api_token }}"

    - name: Include register host task
      include_tasks: playbooks/tasks/register_host.yml
      vars:
        docker_installed: "{{ hostvars[inventory_hostname].docker_installed | default(false) }}"
