---
all:
  children:
    new_servers:
      hosts:
        new-server-20:
          ansible_host: 152.53.153.74
          ansible_user: root
          ansible_port: 22
          ansible_password: xItl11unREZldge
          server_domain: "vpn-20.tgvpnbot.com"
          ansible_ssh_common_args: "-o PasswordAuthentication=yes -o PubkeyAuthentication=no"
          server_name: "server-20"

        new-server-21:
          ansible_host: 152.53.152.244
          ansible_user: root
          ansible_port: 22
          ansible_password: ZZ82xOHaJzJV8TA
          server_domain: "vpn-21.tgvpnbot.com"
          ansible_ssh_common_args: "-o PasswordAuthentication=yes -o PubkeyAuthentication=no"
          server_name: "server-21"

        new-server-22:
          ansible_host: 152.53.155.168
          ansible_user: root
          ansible_port: 22
          ansible_password: 6gs8f1fXIJ5vZph
          server_domain: "vpn-22.tgvpnbot.com"
          ansible_ssh_common_args: "-o PasswordAuthentication=yes -o PubkeyAuthentication=no"
          server_name: "server-22"

        new-server-23:
          ansible_host: 152.53.153.152
          ansible_user: root
          ansible_port: 22
          ansible_password: NpBumTLj5Gmnuag
          server_domain: "vpn-23.tgvpnbot.com"
          ansible_ssh_common_args: "-o PasswordAuthentication=yes -o PubkeyAuthentication=no"
          server_name: "server-23"

        new-server-24:
          ansible_host: 152.53.152.195
          ansible_user: root
          ansible_port: 22
          ansible_password: 2Uau6gdqdVv8Azd
          server_domain: "vpn-24.tgvpnbot.com"
          ansible_ssh_common_args: "-o PasswordAuthentication=yes -o PubkeyAuthentication=no"
          server_name: "server-24"


  hosts:
    localhost:
      ansible_connection: local
