---
- name: 🔄 Синхронизировать активные ноды Remnawave с DNS A-записями в Porkbun
  hosts: localhost
  gather_facts: no

  vars:
    # Работаем напрямую с target_domains — это домены 2-го уровня (apex)
    domains_to_process: "{{ target_domains }}"

  tasks:

    # --- ШАГ 1: Получить список активных нод из Remnawave API ---
    - name: 🌐 Получить активные ноды из Remnawave
      uri:
        url: "https://{{ remnawave_domain }}/api/nodes"
        method: GET
        headers:
          Authorization: "Bearer {{ remnawave_token }}"
        return_content: yes
        timeout: 30
      register: remnawave_response
      until: remnawave_response.status == 200
      retries: 3
      delay: 5

    - name: ❌ Проверить ошибку Remnawave API
      fail:
        msg: "Remnawave API вернул ошибку: {{ remnawave_response.json.message | default('Unknown error') }}"
      when: remnawave_response.json is defined and remnawave_response.json.errorCode is defined

    - name: 🧩 Извлечь активные ноды (isNodeOnline == true)
      set_fact:
        active_nodes: >-
          {{
            remnawave_response.json.response
            | selectattr('isNodeOnline', 'equalto', true)
            | list
          }}

    - name: 📄 Вывести список активных нод
      debug:
        msg: |-
          АКТИВНЫЕ НОДЫ ({{ active_nodes | length }} шт.):
          {% for node in active_nodes %}
          {{ "%2d" % loop.index }}) {{ node.name }} → {{ node.address }}
          {% endfor %}
      when: active_nodes | length > 0

    - name: 🟡 Нет активных нод — пропускаем DNS-операции
      debug:
        msg: "Нет активных нод в Remnawave. Ничего делать не нужно."
      when: active_nodes | length == 0

    # --- ШАГ 2: Для каждого домена получить все DNS-записи ---
    - name: 🔍 Получить все DNS-записи для домена
      uri:
        url: "https://api.porkbun.com/api/json/v3/dns/retrieve/{{ item }}"
        method: POST
        body:
          apikey: "{{ porkbun_api_key }}"
          secretapikey: "{{ porkbun_secret_api_key }}"
        body_format: json
        return_content: yes
      register: dns_retrieve_results
      ignore_errors: yes
      loop: "{{ domains_to_process }}"
      loop_control:
        label: "{{ item }}"

    # --- ДЕБАГ: Вывести сырые DNS-записи для отладки ---
    - name: 🐞 DEBUG — Сырые DNS-записи для домена
      debug:
        var: result.json.records
      loop: "{{ domains_to_process }}"
      loop_control:
        label: "{{ item }}"
      vars:
        result: "{{ dns_retrieve_results.results | selectattr('item', 'equalto', item) | first }}"
      when: result.json is defined and result.json.status == "SUCCESS"

    # --- ШАГ 3: Проверить ошибки Porkbun API ---
    - name: ❌ Проверить ошибку Porkbun API для домена
      fail:
        msg: "Porkbun API error for {{ item }}: {{ result.json.message | default('Unknown') }}"
      when: result.json is defined and result.json.status != "SUCCESS"
      loop: "{{ domains_to_process }}"
      loop_control:
        label: "{{ item }}"
      vars:
        result: "{{ dns_retrieve_results.results | selectattr('item', 'equalto', item) | first }}"

    - name: 🧩 Построить existing_ips_map (только A-записи для apex-домена)
      set_fact:
        existing_ips_map: >-
          {{
            existing_ips_map | default({}) | combine({
              item: (
                (
                  (dns_retrieve_results.results | selectattr('item', 'equalto', item) | first | default({}))
                  .json.records | default([])
                )
                | selectattr('type', 'equalto', 'A')
                | selectattr('name', 'equalto', item)
                | map(attribute='content')
                | map('trim')
                | list
                | unique
              )
            })
          }}
      loop: "{{ domains_to_process }}"
      loop_control:
        label: "{{ item }}"

    # --- ДЕБАГ: Вывести existing_ips_map ---
    - name: 🐞 DEBUG — existing_ips_map (текущие IP по доменам)
      debug:
        var: existing_ips_map

    - name: 🚀 Создать отсутствующие A-записи (для apex-домена)
      uri:
        url: "https://api.porkbun.com/api/json/v3/dns/create/{{ domain }}"
        method: POST
        body:
          apikey: "{{ porkbun_api_key }}"
          secretapikey: "{{ porkbun_secret_api_key }}"
          name: ""
          type: "A"
          content: "{{ node.address }}"
          ttl: "300"
        body_format: json
        status_code: 200
      loop: "{{ active_nodes | product(domains_to_process) | list }}"
      loop_control:
        loop_var: pair
        label: "{{ pair.1 }} → {{ pair.0.address }}"
      vars:
        node: "{{ pair.0 }}"
        domain: "{{ pair.1 }}"
        existing_ips: "{{ existing_ips_map[domain] | default([]) | map('trim') | list }}"
        active_ip: "{{ node.address | trim }}"
      when:
        - active_nodes | length > 0
        - active_ip not in existing_ips
      register: create_results

    # --- ДЕБАГ: Сравнение IP по доменам ---
    - name: 🐞 DEBUG — Сравнение IP по домену
      debug:
        msg: |-
          Домен: {{ domain }}
          Активные IP: {{ active_ips }}
          Существующие IP: {{ existing_ips }}
          Отсутствующие IP: {{ missing_ips }}
      loop: "{{ domains_to_process }}"
      loop_control:
        label: "{{ domain }}"
      vars:
        domain: "{{ item }}"
        existing_ips: "{{ existing_ips_map[item] | default([]) | map('trim') | list }}"
        active_ips: "{{ active_nodes | map(attribute='address') | map('trim') | list | unique }}"
        missing_ips: "{{ active_ips | difference(existing_ips) }}"

    # --- Уведомление: сколько записей создано по каждому домену ---
    - name: ✅ Успешно созданы записи — сводка по доменам
      debug:
        msg: "✅ В домене {{ domain }} создано A-записей: {{ count }}"
      loop: "{{ domains_to_process }}"
      loop_control:
        label: "{{ domain }}"
      vars:
        domain: "{{ item }}"
        count: >-
          {% set records = create_results.results | default([]) %}
          {% set total = 0 %}
          {% for rec in records %}
            {% if rec.changed is defined and rec.changed and rec.item is defined and rec.item | length >= 2 and rec.item[1] == domain %}
              {% set total = total + 1 %}
            {% endif %}
          {% endfor %}
          {{ total }}

    # --- Уведомление: если создавать нечего ---
    - name: ℹ️ Записи не требуются — все IP уже есть
      debug:
        msg: "ℹ️ Все активные ноды уже имеют A-записи в домене {{ domain }}"
      loop: "{{ domains_to_process }}"
      loop_control:
        label: "{{ domain }}"
      vars:
        domain: "{{ item }}"
        existing_ips: "{{ existing_ips_map[item] | default([]) | map('trim') | list }}"
        active_ips: "{{ active_nodes | map(attribute='address') | map('trim') | list | unique }}"
        missing: "{{ active_ips | difference(existing_ips) }}"
      when: missing | length == 0

    # --- ФИНАЛ: Итоговая сводка ---
    - name: 📊 Итоговая сводка
      debug:
        msg: |-

          Синхронизация DNS завершена.

          Активных нод {{ active_nodes | length }}

          Целевых доменов {{ domains_to_process | length }}

      when: active_nodes | length > 0

    - name: 📊 Синхронизация не требовалась — нод нет
      debug:
        msg: "ℹ️ Синхронизация не проводилась — активных нод не обнаружено."
      when: active_nodes | length == 0
