---
- name: Базовая часть подготовки системы
  hosts: new_servers
  become: yes
  serial: 1
  gather_facts: yes

  tasks:
      - name: Создать директорию для логов xray
        file:
            path: /var/log/xray
            state: directory
            mode: "0755"
            owner: root
            group: root

      - name: Обновить список пакетов
        apt:
            update_cache: yes
            cache_valid_time: 3600

      - name: Установить необходимые пакеты
        apt:
            name:
                - sudo
                - unzip
                - figlet
                - wget
                - certbot
                - fail2ban
            state: present
