- name: Установка obt
  hosts: new_servers
  become: yes
  vars:
      obt_binary_url: "https://backups.tgvpnbot.com/ritascarlet/OBT/raw/branch/main/obt"
      obt_service_user: root
      obt_backup_time: "00:00"

  tasks:
      - name: Скачать бинарник obt
        ansible.builtin.get_url:
            url: "{{ obt_binary_url }}"
            dest: /usr/local/bin/obt
            mode: "0755"
            force: yes

      - name: Создание директории obt
        ansible.builtin.file:
            path: /root/.config/obt
            state: directory
            mode: "0755"
            owner: root
            group: root

      - name: Создать systemd сервис obt.service
        ansible.builtin.copy:
            dest: /etc/systemd/system/obt.service
            content: |
                [Unit]
                Description=OfficialVPN Backup Tool
                After=network.target

                [Service]
                Type=simple
                ExecStart=/usr/local/bin/obt --daemon
                Restart=always
                User=root

                [Install]
                WantedBy=multi-user.target
            mode: "0644"
        notify: reload systemd and restart obt

      - name: Создать systemd таймер obt.timer
        ansible.builtin.copy:
            dest: /etc/systemd/system/obt.timer
            content: |
                [Unit]
                Description=OfficialVPN Backup Tool Timer

                [Timer]
                OnCalendar=*-*-* 00:00:00
                Persistent=true

                [Install]
                WantedBy=timers.target
            mode: "0644"
        notify: reload systemd and restart obt

      - name: Создать конфиг для obt
        ansible.builtin.copy:
            dest: /root/.config/obt/config.json
            content: |
                {
                  "gitea_url": "backups.tgvpnbot.com/kamil",
                  "gitea_repo": "VLESS-Backups",
                  "gitea_username": "ritascarlet",
                  "gitea_password": "AnothGoaGo34",
                  "backup_paths": [
                    "/etc/x-ui/x-ui.db"
                  ],
                  "last_backup": "2025-08-27 13:01:52 MSK",
                  "backup_name": "{{ server_name }}",
                  "backup_frequency": "Daily",
                  "backup_time": "01:00"
                }
            mode: "0644"
        notify: reload systemd and restart obt

      - name: Выполнить команду в bash
        ansible.builtin.shell: |
            sudo obt --daemon
        args:
            executable: /bin/bash

  handlers:
      - name: reload systemd and restart obt
        ansible.builtin.systemd:
            daemon_reload: yes
            name: obt.timer
            enabled: yes
            state: restarted
