---
all:
    children:
        actual_servers:
            hosts:
                server:
                    ansible_host: 85.192.48.110
                    ansible_user: root
                    ansible_port: 11041
                    ansible_ssh_private_key_file: /root/.ssh/id_ed25519
                    server_name: "zabbix-test"
