---
- name: Deploy Caddy with two websites
  hosts: all
  become: yes
  vars:
    base_dir: "/etc/ansible/remnawave/remnanode"
    working_dir: "/opt/caddy"

  tasks:
    # 1) Проверка установки Docker
    - name: Check if Docker is installed
      command: docker --version
      register: docker_check
      ignore_errors: yes
      changed_when: false

    - name: Fail if Docker is not installed
      fail:
        msg: "Docker is not installed. Please install Docker first."
      when: docker_check.rc != 0


    # 2) Создание рабочих директорий на удаленном сервере
    - name: Create working directories on server
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ working_dir }}"
        - "{{ working_dir }}/data"
        - "{{ working_dir }}/logs"
        - "/var/www/mos-drywall.shop"
        - "/var/www/my-rebar.shop"

    # 3) Копирование Caddyfile из локальной папки caddy/
    - name: Copy Caddyfile
      copy:
        src: "{{ base_dir }}/caddy/Caddyfile"
        dest: "{{ working_dir }}/Caddyfile"
        mode: '0644'

    # 4) Копирование файлов сайтов из локальных папок
    - name: Copy mos-drywall.shop website files
      copy:
        src: "{{ base_dir }}/mos-drywall.shop/"
        dest: "/var/www/mos-drywall.shop/"
        mode: '0644'
        directory_mode: '0755'

    - name: Copy my-rebar.shop website files
      copy:
        src: "{{ base_dir }}/my-rebar.shop/"
        dest: "/var/www/my-rebar.shop/"
        mode: '0644'
        directory_mode: '0755'

    # 5) Копирование docker-compose.yml из локальной папки caddy/
    - name: Copy docker-compose.yml
      copy:
        src: "{{ base_dir }}/caddy/docker-compose.yml"
        dest: "{{ working_dir }}/docker-compose.yml"
        mode: '0644'

    # 5.1) Копирование Dockerfile из локальной папки caddy/
    - name: Copy Dockerfile
      copy:
        src: "{{ base_dir }}/caddy/Dockerfile"
        dest: "{{ working_dir }}/Dockerfile"
        mode: '0644'

    # 6) Запуск контейнера через Docker Compose\

    - name: Запустить контейнер remnanode через Docker Compose
      shell: |
        docker compose down
      args:
        chdir: "{{ working_dir }}"

    - name: Запустить контейнер remnanode через Docker Compose
      shell: |
        docker compose up -d
      args:
        chdir: "{{ working_dir }}"

    # → Получаем имя контейнера Caddy
    - name: Fetch Caddy container name
      command: >
        docker ps --format "{{'{{.Names}}'}}"
        --filter "name=caddy"
        --filter "status=running"
      register: caddy_container_search
      changed_when: false

    - name: Fail if no running Caddy container found
      fail:
        msg: "No running Caddy container found. Check docker-compose and container status."
      when: caddy_container_search.stdout_lines | length == 0

    - name: Set Caddy container name
      set_fact:
        caddy_container_name: "{{ caddy_container_search.stdout_lines | first }}"

    # 7) Проверка работы сайтов
    - name: Wait for Caddy to start
      wait_for:
        port: 80
        host: 127.0.0.1
        delay: 2
        timeout: 30

    - name: Check HTTP to HTTPS redirect for mos-drywall.shop
      uri:
        url: "http://localhost/"
        method: GET
        headers:
          Host: "mos-drywall.shop"
        status_code: 301
        follow_redirects: no
      register: redirect_check_mos

    - name: Check HTTP to HTTPS redirect for my-rebar.shop
      uri:
        url: "http://localhost/"
        method: GET
        headers:
          Host: "my-rebar.shop"
        status_code: 301
        follow_redirects: no
      register: redirect_check_rebar

    # Проверяем, установлен ли tree
    - name: Check if 'tree' command is available
      command: which tree
      register: tree_check
      ignore_errors: yes
      changed_when: false

    # Устанавливаем tree, если не найден (Debian/Ubuntu)
    - name: Install tree package (Debian/Ubuntu)
      apt:
        name: tree
        state: present
        update_cache: yes
      when: tree_check.rc != 0 and ansible_os_family == "Debian"

    # Устанавливаем tree, если не найден (RHEL/CentOS/Fedora)
    - name: Install tree package (RHEL/CentOS/Fedora)
      yum:
        name: tree
        state: present
      when: tree_check.rc != 0 and ansible_os_family == "RedHat"

    - name: Install tree package (AlmaLinux/Rocky Linux)
      dnf:
        name: tree
        state: present
      when: tree_check.rc != 0 and ansible_os_family == "RedHat" and ansible_distribution in ["AlmaLinux", "Rocky"]

    # Выполняем и выводим tree
    - name: Show directory structure with tree
      command: tree "{{ working_dir }}"
      register: tree_output
      changed_when: false

    - name: Display tree output
      debug:
        msg: |
          🌲 Directory Structure:
          {{ tree_output.stdout }}


    # 12) Вывод результатов
    - name: Show deployment and SSL results
      debug:
        msg:
          - "✅ remnanode container running"
          - "✅ Caddy started and obtained certificate for mos-drywall.shop => {{ mos_cert_obtained }}"
          - "🔁 mos-drywall.shop redirect => {{ redirect_check_mos.status | default('n/a') }}"
          - "🔁 my-rebar.shop redirect => {{ redirect_check_rebar.status | default('n/a') }}"
