---
all:
    children:
        servers:
            hosts:
                server-1:
                    ansible_host: 86.106.183.35
                    ansible_user: backups
                    ansible_port: 11041
                    server_name: "backups"


