---
- name: Обновить Xray Core в 3x-ui
  hosts: new_servers
  serial: 1
  become: yes
  vars:
      xui_install_path: "/usr/local/x-ui"
      xray_binary_path: "{{ xui_install_path }}/bin/xray-linux-amd64"
      xray_backup_path: "{{ xui_install_path }}/bin/xray-linux-amd64.backup"
      xray_download_url: "https://github.com/XTLS/Xray-core/releases/download/v25.5.16/Xray-linux-64.zip"
      xray_temp_dir: "/tmp/xray_update"
  environment:
      TMPDIR: /tmp

  tasks:
      - name: Остановить службу 3x-ui
        systemd:
            name: x-ui
            state: stopped
        ignore_errors: yes

      - name: Создать .ansible директорию для vpnuser
        file:
            path: "/home/vpnuser/.ansible/tmp"
            state: directory
            mode: "0755"
            owner: vpnuser
            group: vpnuser

      - name: Создать директорию для временных файлов Ansible
        file:
            path: /tmp/.ansible/tmp
            state: directory
            mode: "0755"
            owner: vpnuser

      - name: Создать временную директорию для загрузки
        file:
            path: "{{ xray_temp_dir }}"
            state: directory
            mode: "0755"

      - name: Скачать последнюю версию Xray Core
        get_url:
            url: "{{ xray_download_url }}"
            dest: "{{ xray_temp_dir }}/xray_latest.zip"
            mode: "0644"

      - name: Распаковать архив с Xray
        unarchive:
            src: "{{ xray_temp_dir }}/xray_latest.zip"
            dest: "{{ xray_temp_dir }}"
            remote_src: yes

      - name: Сделать бэкап текущего бинарника Xray
        copy:
            src: "{{ xray_binary_path }}"
            dest: "{{ xray_backup_path }}"
            remote_src: yes
        ignore_errors: yes

      - name: Заменить бинарник Xray на новый
        copy:
            src: "{{ xray_temp_dir }}/xray"
            dest: "{{ xray_binary_path }}"
            mode: "0755"
            owner: root
            group: root
            remote_src: yes

      - name: Сделать бинарник исполняемым (дополнительно)
        file:
            path: "{{ xray_binary_path }}"
            mode: "0755"

      - name: Удалить временную директорию
        file:
            path: "{{ xray_temp_dir }}"
            state: absent

      - name: Запустить службу 3x-ui
        systemd:
            name: x-ui
            state: started
            enabled: yes

      - name: Проверить версию нового Xray Core
        command: "{{ xray_binary_path }} --version"
        register: xray_version
        changed_when: false

      - name: Вывести версию Xray Core
        debug:
            msg: "Установлена версия Xray Core: {{ xray_version.stdout }}"

      - name: Запустить службу 3x-ui
        systemd:
            name: x-ui
            state: restarted
            enabled: yes
