---
- name: Настройка 3x-ui
  hosts: new_servers
  serial: 1
  become: yes
  vars:
      xui_web_port: 65502
      xui_sub_port: 3296
      xui_time_location: "Europe/Moscow"
  tasks:
      - name: Создать директорию для логов x-ui
        file:
            path: /var/log/x-ui
            state: directory
            mode: "0755"
            owner: root
            group: root

      - name: Настроить права доступа к базе данных
        file:
            path: /etc/x-ui/x-ui.db
            owner: root
            group: root
            mode: "0644"

      - name: Перезапустить 3x-ui сервис
        systemd:
            name: x-ui
            state: restarted
            enabled: yes

      - name: Проверить статус 3x-ui
        systemd:
            name: x-ui
            state: started

      - name: Установить параметры ядра для BBR (але?)
        sysctl:
            name: "{{ item.name }}"
            value: "{{ item.value }}"
            sysctl_set: yes
            state: present
            reload: yes
        loop:
            - { name: "net.core.default_qdisc", value: "fq" }
            - { name: "net.ipv4.tcp_congestion_control", value: "bbr" }

      - name: Убедиться что BBR загружен
        modprobe:
            name: tcp_bbr
            state: present
