---
- name: 📋 Показать все A-записи домена
  hosts: localhost
  gather_facts: no
  vars_files:
      - /etc/ansible/migration/inventory/porkbun.yml

  tasks:
      - name: 🔍 Получить все DNS-записи из Porkbun
        uri:
            url: "https://api.porkbun.com/api/json/v3/dns/retrieve/{{ porkbun_domain }}"
            method: POST
            body:
                apikey: "{{ porkbun_api_key }}"
                secretapikey: "{{ porkbun_secret_api_key }}"
            body_format: json
            return_content: yes
        register: dns_response

      - name: ⚠️ ПроверкаAPI вернул ошибку
        fail:
            msg: "❌ Ошибка API Porkbun: {{ dns_response.json.status }} — {{ dns_response.json.message | default('Unknown error') }}"
        when: dns_response.json is defined and dns_response.json.status != "SUCCESS"

      - name: 🧩 Извлечь и отсортировать A-записи
        set_fact:
            a_records: >-
                {{
                  dns_response.json.records
                  | selectattr('type', 'equalto', 'A')
                  | sort(attribute='name')
                  | list
                }}

      - name: 📄 Вывести список всех A-записей
        debug:
            msg: |-
                СПИСОК A-ЗАПИСЕЙ ДЛЯ {{ porkbun_domain }}

                {% for record in a_records %}
                {{ "%2d" % loop.index }}) {{ "%-30s" % record.name }} → {{ record.content }}
                {% endfor %}
        when: a_records | length > 0

      - name: 🟡 Нет A-записей
        debug:
            msg: |-
                📭 НЕТ A-ЗАПИСЕЙ для домена: {{ porkbun_domain }}
        when: a_records | length == 0
