# playbooks/delete_record.yml
---
- name: ❌ Удалить A-запись по субдомену и IP
  hosts: localhost
  gather_facts: no

  tasks:
    - name: 🔍 Получить все DNS-записи из Porkbun
      uri:
        url: "https://api.porkbun.com/api/json/v3/dns/retrieve/{{ porkbun_domain }}"
        method: POST
        body:
          apikey: "{{ porkbun_api_key }}"
          secretapikey: "{{ porkbun_secret_api_key }}"
        body_format: json
        return_content: yes
      register: dns_response

    - name: ❌ Прервать выполнение при ошибке API
      fail:
        msg: "Ошибка API Porkbun {{ dns_response.json.status }} — {{ dns_response.json.message | default('Unknown error') }}"
      when: dns_response.json is defined and dns_response.json.status != "SUCCESS"

    - name: 🧩 Извлечь и отсортировать A-записи
      set_fact:
        a_records: >-
          {{
            dns_response.json.records
            | selectattr('type', 'equalto', 'A')
            | sort(attribute='name')
            | list
          }}

    - name: 📄 Вывести список всех A-записей
      debug:
        msg: |-
          СПИСОК A-ЗАПИСЕЙ ДЛЯ {{ porkbun_domain }}

          {% for record in a_records %}
          {{ "%2d" % loop.index }}) {{ "%-30s" % record.name }} → {{ record.content }}
          {% endfor %}
      when: a_records | length > 0

    - name: 🟡 Нет A-записей для домена
      debug:
        msg: |-
           НЕТ A-ЗАПИСЕЙ для домена {{ porkbun_domain }}
      when: a_records | length == 0

    - name: 🧩 Запросить имя субдомена
      pause:
        prompt: "Введите имя субдомена (например, demo) для домена 2-го уровня {{ porkbun_domain }}"
      register: subdomain_input

    - name: 🧩 Запросить IP-адрес
      pause:
        prompt: "Введите IP-адрес (например, 1.1.1.1)"
      register: target_ip_input

    - name: 🧩 Сохранить введённые значения
      set_fact:
        subdomain: "{{ subdomain_input.user_input }}"
        target_ip: "{{ target_ip_input.user_input }}"

    - name: 🧩 Найти A-запись с именем {{ subdomain }} и IP {{ target_ip }}
      set_fact:
        target_record: "{{ item }}"
      loop: "{{ dns_response.json.records }}"
      when: >
        item.type == 'A' and
        item.name == (subdomain + '.' + porkbun_domain) and
        item.content == target_ip | trim

    - name: 🚫 Нет совпадающей A-записи
      debug:
        msg: "❌ Не найдено A-записи {{ subdomain }}.{{ porkbun_domain }} → {{ target_ip }}"
      when: target_record is not defined

    - name: 🛑 Подтвердите добавление записи
      pause:
        prompt: "Введите 'yes' для подтверждения добавления, или нажмите Ctrl+C для отмены"
      register: confirmation_pause
      when: target_record is defined

    - name: 🗑️ Удалить A-запись через API
      uri:
        url: "https://api.porkbun.com/api/json/v3/dns/delete/{{ porkbun_domain }}/{{ target_record.id }}"
        method: POST
        body:
          apikey: "{{ porkbun_api_key }}"
          secretapikey: "{{ porkbun_secret_api_key }}"
        body_format: json
        status_code: 200
      register: delete_result
      when: target_record is defined

    - name: ✅ Отчёт об удалении
      debug:
        msg: >-
          {% if delete_result is succeeded %}
          ✅ Успешно удалена {{ subdomain }}.{{ porkbun_domain }} → {{ target_ip }}
          {% else %}
          ❌ Ошибка при удалении {{ delete_result.status }} {{ delete_result.status_text }}
          {% endif %}
      when: target_record is defined
