# playbooks/delete_record.yml
---
- name: ❌ Удалить A-запись по субдомену и IP
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../porkbun.yml

  vars_prompt:
    - name: subdomain
      prompt: "Имя субдомена (например, demo или blog)"
      private: no
    - name: target_ip
      prompt: "IP-адрес для удаления (например, 1.1.1.1)"
      private: no

  tasks:
    - name: 🧪 Проверка переменных
      debug:
        msg: |
          Domain: {{ porkbun_domain }}
          Subdomain: {{ subdomain }}
          Target IP: {{ target_ip }}

    - name: 🔍 Получить все DNS-записи из Porkbun
      uri:
        url: "https://api.porkbun.com/api/json/v3/dns/retrieve/{{ porkbun_domain }}"
        method: POST
        body:
          apikey: "{{ porkbun_api_key }}"
          secretapikey: "{{ porkbun_secret_api_key }}"
        body_format: json
        return_content: yes
      register: dns_response

    - name: ⚠️ ПроверкаAPI вернул ошибку
      fail:
        msg: "❌ Ошибка API {{ dns_response.json.status }} — {{ dns_response.json.message | default('Unknown error') }}"
      when: dns_response.json is defined and dns_response.json.status != "SUCCESS"

    - name: 🧩 Найти A-запись с именем {{ subdomain }} и IP {{ target_ip }}
      set_fact:
        target_record: "{{ item }}"
      loop: "{{ dns_response.json.records }}"
      when: >
        item.type == 'A' and
        item.name == (subdomain + '.' + porkbun_domain) and
        item.content == target_ip | trim

    - name: 🚫 Нет совпадающей A-записи
      debug:
        msg: "❌ Не найдено A-записи {{ subdomain }}.{{ porkbun_domain }} → {{ target_ip }}"
      when: target_record is not defined

    - name: 🗑️ Удалить A-запись через API
      uri:
        url: "https://api.porkbun.com/api/json/v3/dns/delete/{{ porkbun_domain }}/{{ target_record.id }}"
        method: POST
        body:
          apikey: "{{ porkbun_api_key }}"
          secretapikey: "{{ porkbun_secret_api_key }}"
        body_format: json
        status_code: 200
      register: delete_result
      when: target_record is defined

    - name: ✅ Отчёт об удалении
      debug:
        msg: >-
          {% if delete_result is succeeded %}
          ✅ Успешно удалена {{ subdomain }}.{{ porkbun_domain }} → {{ target_ip }}
          {% else %}
          ❌ Ошибка при удалении {{ delete_result.status }} {{ delete_result.status_text }}
          {% endif %}
      when: target_record is defined
