---
- name: 🗑️ Удалить A-записи для неактивных нод Remnawave из DNS Porkbun
  hosts: localhost
  gather_facts: no

  vars:
    domains_to_process: "{{ target_domains }}"

  tasks:

    # --- ШАГ 1: Получить активные ноды из Remnawave API ---
    - name: 🌐 Получить активные ноды из Remnawave
      uri:
        url: "https://{{ remnawave_domail }}/api/nodes"
        method: GET
        headers:
          Authorization: "Bearer {{ remnawave_token }}"
        return_content: yes
        timeout: 30
      register: remnawave_response
      until: remnawave_response.status == 200
      retries: 3
      delay: 5

    - name: ❌ Проверить ошибку Remnawave API
      fail:
        msg: "Remnawave API вернул ошибку: {{ remnawave_response.json.message | default('Unknown error') }}"
      when: remnawave_response.json is defined and remnawave_response.json.errorCode is defined

    - name: 🧩 Извлечь активные ноды (isNodeOnline == true)
      set_fact:
        active_nodes: >-
          {{
            remnawave_response.json.response
            | selectattr('isNodeOnline', 'equalto', true)
            | list
          }}

    - name: 📄 Вывести список активных нод
      debug:
        msg: |-
          АКТИВНЫЕ НОДЫ ({{ active_nodes | length }} шт.):
          {% for node in active_nodes %}
          {{ "%2d" % loop.index }}) {{ node.name }} → {{ node.address }}
          {% endfor %}
      when: active_nodes | length > 0

    - name: 🟡 Нет активных нод — пропускаем DNS-операции
      debug:
        msg: "Нет активных нод в Remnawave. Удалять нечего."
      when: active_nodes | length == 0

    # --- ШАГ 2: Для каждого домена получить все DNS-записи ---
    - name: 🔍 Получить все DNS-записи для домена
      uri:
        url: "https://api.porkbun.com/api/json/v3/dns/retrieve/{{ item }}"
        method: POST
        body:
          apikey: "{{ porkbun_api_key }}"
          secretapikey: "{{ porkbun_secret_api_key }}"
        body_format: json
        return_content: yes
      register: dns_retrieve_results
      ignore_errors: yes
      loop: "{{ domains_to_process }}"
      loop_control:
        label: "{{ item }}"

    # --- ШАГ 3: Проверить ошибки Porkbun API ---
    - name: ❌ Проверить ошибку Porkbun API для домена
      fail:
        msg: "Porkbun API error for {{ item }}: {{ result.json.message | default('Unknown') }}"
      when: result.json is defined and result.json.status != "SUCCESS"
      loop: "{{ domains_to_process }}"
      loop_control:
        label: "{{ item }}"
      vars:
        result: "{{ dns_retrieve_results.results | selectattr('item', 'equalto', item) | first }}"

    # --- ШАГ 4 Построить existing_a_records_map — все A-записи apex-домена ---
    # --- ШАГ 4: Построить existing_a_records_map — все A-записи apex-домена ---
    - name: 🧩 Построить existing_a_records_map (только A-записи для apex-домена)
      set_fact:
        existing_a_records_map: >-
          {{
            existing_a_records_map | default({}) | combine({
              item: (
                (
                  (dns_retrieve_results.results | selectattr('item', 'equalto', item) | first | default({}))
                  .json.records | default([])
                )
                | selectattr('type', 'equalto', 'A')
                | selectattr('name', 'equalto', item)
                | map(attribute='content') | map('trim') | list as contents
                | map(attribute='id') | list as ids
                | zip(contents, ids) | map('list') | list
              )
            })
          }}
      loop: "{{ domains_to_process }}"
      loop_control:
        label: "{{ item }}"
      vars:
        # Извлекаем записи для текущего домена
        domain_records: >-
          {{
            (
              (dns_retrieve_results.results | selectattr('item', 'equalto', item) | first | default({}))
              .json.records | default([])
            )
            | selectattr('type', 'equalto', 'A')
            | selectattr('name', 'equalto', item)
          }}
        # Извлекаем списки content и id отдельно
        contents: "{{ domain_records | map(attribute='content') | map('trim') | list }}"
        ids: "{{ domain_records | map(attribute='id') | list }}"
        # Объединяем в список пар [content, id]
        paired_records: "{{ contents | zip(ids) | map('list') | list }}"
      set_fact:
        existing_a_records_map: >-
          {{
            existing_a_records_map | default({}) | combine({
              item: paired_records
            })
          }}
    # --- ШАГ 5: Построить множество активных IP ---
    - name: 🧩 Извлечь множество активных IP
      set_fact:
        active_ips_set: "{{ active_nodes | map(attribute='address') | map('trim') | list | unique }}"

    # --- ШАГ 6: Для каждого домена найти лишние записи (IP не в active_ips_set) ---
    - name: 🧩 Найти лишние A-записи для удаления
      set_fact:
        orphaned_records: >-
          {{
            orphaned_records | default({}) | combine({
              domain: (
                existing_a_records_map[domain] | default([])
                | rejectattr(0, 'in', active_ips_set)
                | list
              )
            })
          }}
      loop: "{{ domains_to_process }}"
      loop_control:
        loop_var: domain
      vars:
        active_ips_set: "{{ active_nodes | map(attribute='address') | map('trim') | list | unique }}"

    # --- ДЕБАГ: Вывести orphaned_records ---
    - name: 🐞 DEBUG — orphaned_records (IP → ID для удаления)
      debug:
        var: orphaned_records

    # --- ШАГ 7: Вывести сводку по доменам — что будет удалено ---
    - name: 📄 Сводка записи для удаления по доменам
      debug:
        msg: |-
          ДОМЕН: {{ domain }}
          Найдено лишних записей: {{ count }}
          {% for ip, id in records %}
          → {{ ip }} (ID: {{ id }})
          {% endfor %}
      loop: "{{ orphaned_records | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      vars:
        domain: "{{ item.key }}"
        records: "{{ item.value }}"
        count: "{{ item.value | length }}"

    - name: 🛑 Подтвердите удаление записей (введите 'yes')
      pause:
        prompt: "⚠️ Будет удалено {{ total_orphaned }} записей. Введите 'yes' для подтверждения, или Ctrl+C для отмены"
      register: confirmation
      when: total_orphaned | default(0) | int > 0

    # --- ШАГ 9: Удалить лишние записи через API ---
    - name: 🗑️ Удалить лишние A-записи
      uri:
        url: "https://api.porkbun.com/api/json/v3/dns/delete/{{ domain }}/{{ item.1 }}"
        method: POST
        body:
          apikey: "{{ porkbun_api_key }}"
          secretapikey: "{{ porkbun_secret_api_key }}"
        body_format: json
        status_code: 200
      loop: "{{ orphaned_records | dict2items | subelements('value') }}"
      loop_control:
        label: "{{ item.0.key }} → {{ item.1.0 }} (ID: {{ item.1.1 }})"
      vars:
        domain: "{{ item.0.key }}"
      when: confirmation.user_input | default('no') == 'yes'
      register: delete_results

    # --- ШАГ 10: Отчёт об удалении ---
    - name: ✅ Отчёт успешные удаления
      debug:
        msg: "✅ Удалена запись: {{ domain }} → {{ ip }} (ID: {{ record_id }})"
      loop: "{{ delete_results.results | default([]) }}"
      loop_control:
        label: "{{ item.item.0.key }} → {{ item.item.1.0 }}"
      vars:
        domain: "{{ item.item.0.key }}"
        ip: "{{ item.item.1.0 }}"
        record_id: "{{ item.item.1.1 }}"
      when: item is defined and item.status == 200

    - name: ❌ Отчёт ошибки при удалении
      debug:
        msg: "❌ Ошибка при удалении {{ domain }} → {{ ip }} (ID: {{ record_id }}): {{ item.status }} {{ item.status_text }}"
      loop: "{{ delete_results.results | default([]) }}"
      loop_control:
        label: "{{ item.item.0.key }} → {{ item.item.1.0 }}"
      vars:
        domain: "{{ item.item.0.key }}"
        ip: "{{ item.item.1.0 }}"
        record_id: "{{ item.item.1.1 }}"
      when: item is defined and item.status != 200

    # --- ФИНАЛ: Итоговая сводка (умная версия) ---
    - name: 📊 Финальный отчёт — что было сделано
      debug:
        msg: |-
          {% set total_deleted = (delete_results.results | default([]) | selectattr('status', 'equalto', 200) | list | length) | int %}
          {% if total_deleted > 0 %}
          ✅ УДАЛЕНИЕ ЗАВЕРШЕНО

          Активных нод: {{ active_nodes | length }}
          Доменов обработано: {{ domains_to_process | length }}
          Всего удалено записей: {{ total_deleted }}

          {% else %}
          ℹ️ УДАЛЕНИЕ НЕ ТРЕБОВАЛОСЬ
          {% if active_nodes | length == 0 %}
          → Активных нод не обнаружено.
          {% else %}
          → Все A-записи актуальны — удалять нечего.
          {% endif %}
          {% endif %}
