- hosts: all
  become: true
  vars:
    teleport_package_url: "https://cdn.teleport.dev/teleport_17.7.0_amd64.deb"
    teleport_package_path: "/tmp/teleport-17.7.0.deb"

  tasks:
    - name: Получить Teleport invite token по SSH
      shell: ssh {{ teleport_auth_host }} "sudo tctl tokens add --type=node"
      register: teleport_token_result

    - name: Извлечь сам invite token из вывода
      set_fact:
        teleport_invite_token: "{{ teleport_token_result.stdout | regex_search('token: ([a-zA-Z0-9]+)', '\\1') }}"

    - name: Показать полученный invite token
      debug:
        var: teleport_invite_token
    - name: Проверить, что OS семейства Debian/Ubuntu
      assert:
        that: ansible_facts['os_family'] == 'Debian'
        fail_msg: "Установка только для Debian/Ubuntu!"

    - name: Скачать Teleport DEB
      get_url:
        url: "{{ teleport_package_url }}"
        dest: "{{ teleport_package_path }}"
        mode: '0644'

    - name: Установить Teleport
      apt:
        deb: "{{ teleport_package_path }}"
        state: present

    - name: Развернуть teleport.yaml из текста
      copy:
        dest: /etc/teleport.yaml
        owner: root
        group: root
        mode: '0644'
        content: |
          version: v3
          teleport:
            nodename: ansible
            data_dir: /var/lib/teleport
            join_params:
              token_name: "{{ teleport_invite_token }}"
              method: token
            proxy_server: teleport.tgvpnbot.com:443
            log:
              output: stderr
              severity: INFO
              format:
                output: text
            ca_pin: sha256:15069b6d75043ab3cc8ebf8a312e6f95b2d82c30bee210e49b5f7e6498c378b9
            diag_addr: ""
          auth_service:
            enabled: "no"
          ssh_service:
            enabled: "yes"
            labels:
              infrastructure: ansible
              teleport.internal/resource-id: aa08deb2-2646-4b21-aacc-cd14e573c243
          proxy_service:
            enabled: "no"
            https_keypairs: []
            https_keypairs_reload_interval: 0s
            acme: {}

    - name: Перечитать systemd (на всякий случай)
      command: systemctl daemon-reload
      changed_when: false

    - name: Включить и запустить teleport
      systemd:
        name: teleport
        state: restarted
        enabled: yes
