- hosts: all
  become: true

  tasks:
  - name: Set Teleport repo URL based on OS
    set_fact:
      zabbix_repo_url: >-
        {% if ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] | lower == 'ubuntu' %}
          https://cdn.teleport.dev/teleport_17.7.0_amd64.deb
        {% elif ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] | lower == 'debian' %}
          https://cdn.teleport.dev/teleport_17.7.0_amd64.deb
        {% else %}
          ""
        {% endif %}

    - name: Show which OS and repo URL will be used
      debug:
        msg: "Detected OS: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} → Repo: {{ teleport_repo_url }}"

    - name: Download Teleport repository package
      get_url:
        url: "{{ zabbix_repo_url }}"
        dest: /tmp/teleport-17.7.0.deb
        mode: '0644'
      when: teleport_repo_url != ""

    - name: Install Teleport repository
      apt:
        deb: /tmp/teleport-17.7.0.deb
        state: present
      when: teleport_repo_url != ""

    - name: Deploy teleport.yaml (with proper nodename and label)
      template:
        src: teleport.yaml.j2
        dest: /etc/teleport.yaml
        owner: root
        group: root
        mode: 0644

    - name: Ensure teleport.service.d directory exists
      file:
        path: /etc/systemd/system/teleport.service.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create *основной systemd unit-файл* teleport
      copy:
        dest: /etc/systemd/system/teleport.service
        content: |
          [Unit]
          Description=Teleport SSH Service
          After=network.target

          [Service]
          ExecStart=/usr/bin/teleport start --config=/etc/teleport.yaml
          Restart=always
          LimitNOFILE=1048576

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: 0644
      notify: Reload systemd

    - name: Create Teleport systemd unit override (if required)
      copy:
        dest: /etc/systemd/system/teleport.service.d/override.conf
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/teleport start --config=/etc/teleport.yaml --token={{ teleport_token }} --auth-server={{ teleport_auth_server }}
        owner: root
        group: root
        mode: 0644
      notify: Reload systemd

    - name: Enable and restart Teleport service
      systemd:
        name: teleport
        state: restarted
        enabled: yes

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload
